from pydantic import BaseModel
from typing import List, Optional

class ProjectTableColumnSchema(BaseModel):
    id: int
    nativeColumnName: str
    isPrimaryKey: bool
    foreignKeyFor: Optional[str]
    dataType: str
    description: str
    descriptionsAutoGenerated: bool
    projectTables_id: int
    projects_id: int

    class Config:
        orm_mode = True


class ProjectTableSchema(BaseModel):
    id: int
    nativeTableName: str
    primaryKeyDetected: bool
    description: str
    descriptionAutoGenerated: bool
    columnCount: int
    database_id: int
    projects_id: int
    columns: List[ProjectTableColumnSchema]

    class Config:
        orm_mode = True
