import { useQuery } from "@tanstack/react-query";

export type TableData = {
    id: string;
    nativeTableName: string;
    primaryKeyDetected: boolean;
    description: string;
    descriptionAutoGenerated: boolean;
    columnCount: number;
    database_id: string; //id of the database origin
    projects_id: number;
    table_name: string;
    table_nameAutoGenerated: boolean;
    columns: [];
};

const mockData: TableData[] = [
    {
        id: "1",
        description: "Description of table 1 here Description of table 1 here Description of table 1 here Description of table 1 here ... Description of table 1 here Description of table 1 here Description of table 1 here Description of table 1 here ",
        columnCount: 5,
        database_id: "1",
        descriptionAutoGenerated: false,
        nativeTableName: "Table 1",
        projects_id: 1,
        primaryKeyDetected: true,
        columns: [],
        table_name: "Table 1",
        table_nameAutoGenerated: true,
    },
    {
        id: "2",
        description: "Description of table 1 here ...",
        columnCount: 15,
        database_id: "1",
        descriptionAutoGenerated: true,
        nativeTableName: "Table 2",
        projects_id: 1,
        primaryKeyDetected: true,
        columns: [],
        table_name: "Table 2",
        table_nameAutoGenerated: false,
    },
    {
        id: "3",
        description: "Description of table 1 here ...",
        columnCount: 3,
        database_id: "1",
        descriptionAutoGenerated: false,
        nativeTableName: "Table 3",
        projects_id: 1,
        
        primaryKeyDetected: true,
        columns: [],
        table_name: "Table 3 Pretty Name",
        table_nameAutoGenerated: true,
    }
];

// id = Column(Integer, primary_key=True)
//     nativeTableName = Column(String, unique=True)
//     primaryKeyDetected = Column(Boolean)
//     description = Column(String)
//     descriptionAutoGenerated = Column(Boolean)
//     columnCount = Column(Integer)
//     database_id = Column(Integer)
//     projects_id = Column(Integer)
//     table_name = Column(String)
//     table_nameAutoGenerated = Column(Boolean)

//     # Define a relationship to ProjectTableColumn
//     columns = relationship("ProjectTableColumn", back_populates="table")

export default function useTables() {
    return useQuery({
        queryKey: ["mockTables"],
        queryFn: async () => {
                console.log("Fetching mock table browser data");
                const response: TableData[] = await (await fetch("http://localhost:8000/api/project-tables")).json();
                //const response = mockData;
                console.log("Fetched mock table browser data");
                return response;
        },
    });
}
